import type { IconType } from "react-icons";
import {
  SiNextdotjs,
  SiReact,
  SiTypescript,
  SiJavascript,
  SiHtml5,
  SiTailwindcss,
  SiVite,
  SiNodedotjs,
  SiExpress,
  SiFastapi,
  SiFlask,
  SiPhp,
  SiCodeigniter,
  SiMysql,
  SiPostgresql,
  SiSqlite,
  SiMariadb,
  SiSupabase,
  SiGit,
  SiGithub,
  SiPostman,
  SiDocker,
  SiVercel,
  SiRender,
  SiPython,
} from "react-icons/si";
import { FaCss3Alt } from "react-icons/fa6";

// Every slug used in data/techStack.ts must resolve here. Zustand has no
// icon in the icon sets we use, so it falls back to a text monogram
// (handled in TechPill) rather than breaking the build.
export const techIcons: Record<string, IconType | undefined> = {
  nextjs: SiNextdotjs,
  react: SiReact,
  typescript: SiTypescript,
  javascript: SiJavascript,
  html5: SiHtml5,
  css3: FaCss3Alt,
  tailwindcss: SiTailwindcss,
  vite: SiVite,
  zustand: undefined,
  nodejs: SiNodedotjs,
  express: SiExpress,
  fastapi: SiFastapi,
  flask: SiFlask,
  python: SiPython,
  php: SiPhp,
  codeigniter: SiCodeigniter,
  mysql: SiMysql,
  postgresql: SiPostgresql,
  sqlite: SiSqlite,
  mariadb: SiMariadb,
  supabase: SiSupabase,
  git: SiGit,
  github: SiGithub,
  postman: SiPostman,
  docker: SiDocker,
  vercel: SiVercel,
  render: SiRender,
};
